import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from "react";
import Header from "components/Header";

// Google font for paragraphs
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

// Local font for headers
const bakerSignet = localFont({
  src: "../public/fonts/BakerSignetStd.woff2",
  variable: "--font-baker-signet",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prawns Lake Conservation Project | Eco-Tourism in Kenya's Mangrove Paradise ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${outfit.variable} 
          ${bakerSignet.variable} 
          antialiased
        `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
